apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: loki

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    basicAuth: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
          datasourceUid: prometheus

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    basicAuth: false
    jsonData:
      implementation: prometheus