# BMAD Team Configuration
# Business Model, Architecture, Design workflow coordination

team:
  id: "bmad"
  name: "BMAD Team"
  icon: "🎯"
  description: "Business Model, Architecture, Design workflow - specialized end-to-end product development"
  tier_focus: [1, 2]
  priority: 8
  status: "active"

# Team Members and Roles
members:
  workflow_coordinator:
    agent: "agent-bmad-workflow-coordinator"
    role: "BMAD Workflow Lead & Primary Coordinator"
    responsibilities:
      - "Overall BMAD workflow orchestration"
      - "Phase transition management"
      - "Quality gate enforcement"
      - "Stakeholder coordination"
    authority_level: "workflow_executive"
    
  business_model_lead:
    agent: "agent-bmad-business-model"
    role: "Business Model Design Lead"
    responsibilities:
      - "Business model canvas development"
      - "Value proposition design"
      - "Revenue model strategy"
      - "Market positioning analysis"
    authority_level: "business_executive"
    
  market_researcher:
    agent: "agent-bmad-market-research"
    role: "Market Research & Validation Specialist"
    responsibilities:
      - "Market analysis and research"
      - "Competitive landscape mapping"
      - "Customer validation studies"
      - "Market opportunity assessment"
    authority_level: "research_lead"
    
  architecture_lead:
    agent: "agent-bmad-architecture-design"
    role: "BMAD Architecture Design Lead"
    responsibilities:
      - "Technical architecture design"
      - "System scalability planning"
      - "Technology stack selection"
      - "Integration architecture"
    authority_level: "technical_executive"
    
  technical_planner:
    agent: "agent-bmad-technical-planning"
    role: "Technical Planning & Implementation Specialist"
    responsibilities:
      - "Implementation planning coordination"
      - "Resource estimation and allocation"
      - "Timeline development"
      - "Technical feasibility analysis"
    authority_level: "planning_lead"
    
  design_lead:
    agent: "agent-bmad-design"
    role: "BMAD Design Strategy Lead"
    responsibilities:
      - "Overall design strategy coordination"
      - "Design system architecture"
      - "User experience planning"
      - "Design quality assurance"
    authority_level: "design_executive"
    
  ux_specialist:
    agent: "agent-bmad-user-experience"
    role: "UX Research & Experience Specialist"
    responsibilities:
      - "User experience research"
      - "Journey mapping and optimization"
      - "Usability testing coordination"
      - "User behavior analysis"
    authority_level: "ux_lead"
    
  visual_designer:
    agent: "agent-bmad-visual-design"
    role: "Visual Design & Brand Specialist"
    responsibilities:
      - "Visual design system creation"
      - "Brand identity development"
      - "Graphic design coordination"
      - "Visual consistency assurance"
    authority_level: "design_lead"
    
  validation_specialist:
    agent: "agent-bmad-validation"
    role: "Quality Assurance & Validation Lead"
    responsibilities:
      - "Deliverable validation coordination"
      - "Quality gate enforcement"
      - "Acceptance criteria verification"
      - "Continuous improvement tracking"
    authority_level: "quality_lead"
    
  integration_manager:
    agent: "agent-bmad-integration"
    role: "Core System Integration Manager"
    responsibilities:
      - "BMAD to core system integration"
      - "Knowledge transfer coordination"
      - "Documentation handoff management"
      - "Transition success validation"
    authority_level: "integration_lead"

# Communication Protocols
communication:
  meeting_cadence:
    daily_bmad_sync:
      frequency: "daily"
      duration: "20 minutes"
      participants: ["all_bmad_team"]
      focus: "workflow_progress_blockers"
      
    phase_planning:
      frequency: "phase_start"
      duration: "2 hours"
      participants: ["phase_leads", "stakeholders"]
      focus: "phase_objectives_planning"
      
    quality_gate_review:
      frequency: "phase_end"
      duration: "90 minutes"
      participants: ["validation_team", "approvers"]
      focus: "deliverable_approval"
      
    stakeholder_update:
      frequency: "weekly"
      duration: "45 minutes"
      participants: ["bmad_leads", "core_team_leads"]
      focus: "progress_alignment"

  workflow_communication:
    phase_transitions:
      notification: "automated_stakeholder_notification"
      documentation: "comprehensive_handoff_documentation"
      approval: "formal_approval_process"
      
    cross_team_coordination:
      core_team_updates: "real_time_progress_sharing"
      dependency_management: "proactive_dependency_coordination"
      resource_requests: "formal_resource_request_process"

# Escalation Paths
escalation:
  level_1:
    trigger: "phase_delivery_delays"
    handler: "agent-bmad-workflow-coordinator"
    response_time: "2 hours"
    
  level_2:
    trigger: "quality_gate_failures"
    handler: "agent-bmad-validation"
    response_time: "1 hour"
    
  level_3:
    trigger: "workflow_blocking_issues"
    handler: "agent-master-orchestrator"
    response_time: "30 minutes"
    
  emergency:
    trigger: "critical_bmad_workflow_failures"
    handler: "leadership_team"
    response_time: "immediate"
    notify: ["all_stakeholders"]

# BMAD Workflow Phases
bmad_workflow:
  phase_1_business_model:
    lead_agent: "agent-bmad-business-model"
    supporting_agents: ["agent-bmad-market-research"]
    duration: "2_weeks"
    deliverables:
      - "business_model_canvas"
      - "value_proposition_canvas" 
      - "revenue_model_specification"
      - "market_analysis_report"
      - "competitive_positioning_analysis"
    quality_gates:
      - "stakeholder_approval_business_model"
      - "market_validation_completion"
      - "financial_viability_confirmation"
    success_criteria:
      - "validated_value_proposition"
      - "identified_target_market"
      - "feasible_revenue_model"
    
  phase_2_architecture_design:
    lead_agent: "agent-bmad-architecture-design"
    supporting_agents: ["agent-bmad-technical-planning"]
    duration: "3_weeks"
    deliverables:
      - "system_architecture_document"
      - "technology_stack_recommendation"
      - "scalability_plan"
      - "integration_blueprint"
      - "implementation_plan"
      - "resource_requirements_specification"
    quality_gates:
      - "technical_feasibility_validation"
      - "architecture_review_approval"
      - "resource_availability_confirmation"
    success_criteria:
      - "approved_technical_architecture"
      - "validated_technology_choices"
      - "realistic_implementation_plan"
    
  phase_3_design:
    lead_agent: "agent-bmad-design"
    supporting_agents: ["agent-bmad-user-experience", "agent-bmad-visual-design"]
    duration: "4_weeks"
    deliverables:
      - "user_experience_design"
      - "interface_mockups_prototypes"
      - "design_system_specification"
      - "interactive_prototypes"
      - "usability_testing_results"
      - "design_implementation_guide"
    quality_gates:
      - "usability_testing_approval"
      - "design_system_validation"
      - "stakeholder_design_approval"
    success_criteria:
      - "validated_user_experience"
      - "approved_visual_design"
      - "comprehensive_design_system"
    
  phase_4_validation:
    lead_agent: "agent-bmad-validation"
    supporting_agents: ["all_bmad_agents"]
    duration: "1_week"
    deliverables:
      - "comprehensive_validation_report"
      - "quality_assessment_summary"
      - "compliance_verification"
      - "acceptance_criteria_validation"
      - "improvement_recommendations"
    quality_gates:
      - "all_deliverables_validated"
      - "quality_standards_met"
      - "stakeholder_final_approval"
    success_criteria:
      - "100_percent_validation_success"
      - "all_quality_gates_passed"
      - "ready_for_integration"
    
  phase_5_integration:
    lead_agent: "agent-bmad-integration"
    supporting_agents: ["agent-bmad-workflow-coordinator"]
    duration: "1_week"
    deliverables:
      - "integration_plan_execution"
      - "knowledge_transfer_completion"
      - "documentation_handoff"
      - "transition_success_validation"
      - "lessons_learned_report"
    quality_gates:
      - "successful_core_integration"
      - "complete_knowledge_transfer"
      - "documentation_validation"
    success_criteria:
      - "seamless_core_system_integration"
      - "validated_knowledge_transfer"
      - "sustainable_handoff_completion"

# Integration with Core Teams
core_integration:
  leadership_team:
    coordination_point: "agent-master-orchestrator"
    communication_frequency: "weekly_status_updates"
    decision_authority: "strategic_alignment_approval"
    escalation_path: "direct_executive_escalation"
    
  architecture_team:
    coordination_point: "agent-tech-specs"
    collaboration_areas: ["technical_feasibility", "architecture_validation"]
    handoff_criteria: ["architecture_approval", "implementation_readiness"]
    
  development_team:
    coordination_point: "agent-react-specialist"
    preparation_activities: ["environment_setup", "development_planning"]
    transition_criteria: ["design_specifications_complete", "technical_architecture_approved"]
    
  product_team:
    coordination_point: "agent-product-manager"
    collaboration_areas: ["requirements_validation", "design_approval"]
    feedback_loops: ["user_research_insights", "product_strategy_alignment"]
    
  operations_team:
    coordination_point: "agent-devops-deployment"
    infrastructure_preparation: ["environment_provisioning", "deployment_pipeline_setup"]
    readiness_criteria: ["infrastructure_ready", "monitoring_configured"]

# Quality Assurance Framework
quality_framework:
  quality_standards:
    business_model_quality:
      - "market_validation_completion"
      - "financial_model_accuracy"
      - "value_proposition_clarity"
      - "competitive_differentiation"
      
    architecture_quality:
      - "scalability_requirements_met"
      - "security_standards_compliance"
      - "performance_targets_achievable"
      - "integration_feasibility_validated"
      
    design_quality:
      - "usability_standards_met"
      - "accessibility_compliance_wcag_aa"
      - "brand_consistency_maintained"
      - "user_journey_optimization"
      
  validation_processes:
    peer_review: "mandatory_peer_review_all_deliverables"
    stakeholder_approval: "formal_stakeholder_sign_off"
    compliance_check: "regulatory_compliance_validation"
    integration_testing: "integration_readiness_verification"
    
  continuous_improvement:
    retrospectives: "phase_end_retrospectives"
    metrics_tracking: "quality_metrics_monitoring"
    process_optimization: "workflow_efficiency_improvements"
    lessons_learned: "knowledge_capture_and_sharing"

# Performance Metrics
metrics:
  workflow_performance:
    phase_completion_time: "within_planned_timeline"
    quality_gate_pass_rate: ">95_percent"
    deliverable_acceptance_rate: ">98_percent"
    stakeholder_satisfaction: ">90_percent"
    
  integration_metrics:
    core_integration_success_rate: "100_percent"
    knowledge_transfer_effectiveness: ">95_percent"
    handoff_documentation_completeness: "100_percent"
    transition_success_rate: ">98_percent"
    
  business_impact:
    time_to_market_improvement: "30_percent_faster_than_traditional"
    requirement_accuracy: ">95_percent_requirement_stability"
    design_implementation_fidelity: ">98_percent"
    post_launch_modification_reduction: "50_percent_reduction"
    
  team_collaboration:
    cross_team_satisfaction: ">85_percent"
    communication_effectiveness: ">90_percent"
    conflict_resolution_time: "<24_hours"
    resource_utilization_efficiency: ">85_percent"

# Innovation and Best Practices
innovation:
  methodology_evolution:
    workflow_optimization: "continuous_workflow_improvement"
    tool_integration: "advanced_tooling_adoption"
    automation_opportunities: "process_automation_identification"
    
  knowledge_management:
    best_practices_documentation: "comprehensive_methodology_documentation"
    template_development: "reusable_template_creation"
    training_materials: "bmad_training_program_development"
    
  research_development:
    methodology_research: "bmad_methodology_research"
    industry_benchmarking: "best_practice_benchmarking"
    academic_collaboration: "research_institution_partnerships"

# Technology Stack
technology_stack:
  business_modeling:
    tools: ["strategyzer", "business_model_canvas_tools", "lean_canvas"]
    market_research: ["surveygizmo", "typeform", "google_forms"]
    competitive_analysis: ["similarweb", "semrush", "ahrefs"]
    
  architecture_design:
    modeling: ["lucidchart", "draw_io", "visio"]
    documentation: ["confluence", "notion", "gitbook"]
    collaboration: ["miro", "mural", "conceptboard"]
    
  design_development:
    design_tools: ["figma", "sketch", "adobe_xd"]
    prototyping: ["invision", "principle", "framer"]
    user_testing: ["maze", "usertesting", "hotjar"]
    
  project_management:
    workflow_management: ["asana", "monday", "clickup"]
    documentation: ["confluence", "notion", "coda"]
    communication: ["slack", "microsoft_teams", "discord"]
    
  validation_testing:
    quality_assurance: ["testmo", "zephyr", "xray"]
    user_feedback: ["hotjar", "fullstory", "mixpanel"]
    analytics: ["google_analytics", "amplitude", "heap"]

# Collaboration Patterns
collaboration:
  internal_collaboration:
    cross_phase_coordination: "seamless_phase_transitions"
    knowledge_sharing: "continuous_knowledge_transfer"
    resource_sharing: "flexible_resource_allocation"
    
  external_collaboration:
    stakeholder_engagement: "regular_stakeholder_touchpoints"
    core_team_integration: "embedded_collaboration_model"
    vendor_coordination: "external_vendor_management"
    
  communication_patterns:
    synchronous: "real_time_collaboration_sessions"
    asynchronous: "documented_progress_updates"
    formal: "structured_review_meetings"
    informal: "ad_hoc_consultation_sessions"

# Risk Management
risk_management:
  workflow_risks:
    timeline_risks: "phase_delay_mitigation_strategies"
    quality_risks: "quality_gate_enforcement"
    resource_risks: "resource_availability_planning"
    
  integration_risks:
    handoff_risks: "structured_transition_processes"
    knowledge_loss_risks: "comprehensive_documentation"
    stakeholder_alignment_risks: "continuous_communication"
    
  mitigation_strategies:
    early_detection: "proactive_risk_monitoring"
    rapid_response: "immediate_issue_escalation"
    contingency_planning: "alternative_approach_preparation"

# Integration Points
integration_points:
  upstream_dependencies:
    - "business_strategy_inputs"
    - "market_requirements"
    - "stakeholder_expectations"
    - "regulatory_constraints"
    
  downstream_deliverables:
    - "validated_business_model"
    - "approved_technical_architecture"
    - "comprehensive_design_system"
    - "implementation_ready_specifications"
    
  cross_team_interfaces:
    leadership_team: "strategic_alignment_validation"
    core_teams: "seamless_workflow_integration"
    stakeholders: "continuous_requirement_validation"
    vendors: "external_resource_coordination"

# Success Criteria
success_criteria:
  workflow_success:
    - "all_phases_completed_within_timeline"
    - "quality_gates_passed_successfully"
    - "stakeholder_approval_achieved"
    - "deliverables_meet_acceptance_criteria"
    
  integration_success:
    - "seamless_core_system_handoff"
    - "complete_knowledge_transfer"
    - "sustainable_transition_completion"
    - "post_integration_support_effectiveness"
    
  business_impact:
    - "accelerated_time_to_market"
    - "improved_product_market_fit"
    - "reduced_development_rework"
    - "enhanced_stakeholder_satisfaction"