name: Validate Agent System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check directory structure
      run: |
        echo "Checking required directories..."
        test -d Config_Files || (echo "Config_Files directory missing" && exit 1)
        test -d scripts || (echo "scripts directory missing" && exit 1)
        test -d examples || (echo "examples directory missing" && exit 1)
        test -d docs || (echo "docs directory missing" && exit 1)
        echo "✓ All required directories present"
    
    - name: Count agent files
      run: |
        echo "Counting agent configuration files..."
        AGENT_COUNT=$(ls -1 Config_Files/*.md 2>/dev/null | wc -l)
        echo "Found $AGENT_COUNT agent files"
        if [ "$AGENT_COUNT" -ne 28 ]; then
          echo "ERROR: Expected 28 agents, found $AGENT_COUNT"
          exit 1
        fi
        echo "✓ All 28 agents present"
    
    - name: Validate agent format
      run: |
        echo "Validating agent file format..."
        ERRORS=0
        for agent in Config_Files/*.md; do
          # Check for required frontmatter
          if ! grep -q "^name:" "$agent"; then
            echo "ERROR: $agent missing 'name' field"
            ERRORS=$((ERRORS + 1))
          fi
          if ! grep -q "^description:" "$agent"; then
            echo "ERROR: $agent missing 'description' field"
            ERRORS=$((ERRORS + 1))
          fi
        done
        
        if [ "$ERRORS" -gt 0 ]; then
          echo "Found $ERRORS validation errors"
          exit 1
        fi
        echo "✓ All agents have valid format"
    
    - name: Check documentation
      run: |
        echo "Checking documentation files..."
        test -f README.md || (echo "README.md missing" && exit 1)
        test -f LICENSE || (echo "LICENSE missing" && exit 1)
        test -f QUICK_START.md || (echo "QUICK_START.md missing" && exit 1)
        test -f .gitignore || (echo ".gitignore missing" && exit 1)
        echo "✓ All documentation files present"
    
    - name: Validate scripts
      run: |
        echo "Checking helper scripts..."
        test -x install.sh || (echo "install.sh not executable" && exit 1)
        test -x scripts/validate-agents.sh || (echo "validate-agents.sh not executable" && exit 1)
        test -x scripts/list-agents.sh || (echo "list-agents.sh not executable" && exit 1)
        test -x scripts/update-agents.sh || (echo "update-agents.sh not executable" && exit 1)
        test -x scripts/setup-project.sh || (echo "setup-project.sh not executable" && exit 1)
        echo "✓ All scripts are executable"
    
    - name: List all agents
      run: |
        echo "=== Claude Code Agent System ==="
        echo "Available agents:"
        for agent in Config_Files/*.md; do
          name=$(basename "$agent" .md)
          echo "  - $name"
        done

  test-installation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test installation script
      run: |
        echo "Testing installation script..."
        # Run in test mode (would need to modify install.sh to support --test flag)
        HOME=/tmp/test-home ./install.sh || true
        
        # Check if files would be installed correctly
        echo "✓ Installation script syntax valid"